//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Fortran77Parser.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Fortran77Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IFortran77ParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.commentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommentStatement([NotNull] Fortran77Parser.CommentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.commentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommentStatement([NotNull] Fortran77Parser.CommentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] Fortran77Parser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] Fortran77Parser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.executableUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExecutableUnit([NotNull] Fortran77Parser.ExecutableUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.executableUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExecutableUnit([NotNull] Fortran77Parser.ExecutableUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.mainProgram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainProgram([NotNull] Fortran77Parser.MainProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.mainProgram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainProgram([NotNull] Fortran77Parser.MainProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.functionSubprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionSubprogram([NotNull] Fortran77Parser.FunctionSubprogramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.functionSubprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionSubprogram([NotNull] Fortran77Parser.FunctionSubprogramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.subroutineSubprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubroutineSubprogram([NotNull] Fortran77Parser.SubroutineSubprogramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.subroutineSubprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubroutineSubprogram([NotNull] Fortran77Parser.SubroutineSubprogramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.blockdataSubprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockdataSubprogram([NotNull] Fortran77Parser.BlockdataSubprogramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.blockdataSubprogram"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockdataSubprogram([NotNull] Fortran77Parser.BlockdataSubprogramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.otherSpecificationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOtherSpecificationStatement([NotNull] Fortran77Parser.OtherSpecificationStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.otherSpecificationStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOtherSpecificationStatement([NotNull] Fortran77Parser.OtherSpecificationStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.executableStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExecutableStatement([NotNull] Fortran77Parser.ExecutableStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.executableStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExecutableStatement([NotNull] Fortran77Parser.ExecutableStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.programStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgramStatement([NotNull] Fortran77Parser.ProgramStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.programStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgramStatement([NotNull] Fortran77Parser.ProgramStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.entryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntryStatement([NotNull] Fortran77Parser.EntryStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.entryStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntryStatement([NotNull] Fortran77Parser.EntryStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.functionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionStatement([NotNull] Fortran77Parser.FunctionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.functionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionStatement([NotNull] Fortran77Parser.FunctionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.blockdataStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockdataStatement([NotNull] Fortran77Parser.BlockdataStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.blockdataStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockdataStatement([NotNull] Fortran77Parser.BlockdataStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.subroutineStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubroutineStatement([NotNull] Fortran77Parser.SubroutineStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.subroutineStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubroutineStatement([NotNull] Fortran77Parser.SubroutineStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNamelist([NotNull] Fortran77Parser.NamelistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.namelist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNamelist([NotNull] Fortran77Parser.NamelistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] Fortran77Parser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] Fortran77Parser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.subprogramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubprogramBody([NotNull] Fortran77Parser.SubprogramBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.subprogramBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubprogramBody([NotNull] Fortran77Parser.SubprogramBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.wholeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWholeStatement([NotNull] Fortran77Parser.WholeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.wholeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWholeStatement([NotNull] Fortran77Parser.WholeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.endStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndStatement([NotNull] Fortran77Parser.EndStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.endStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndStatement([NotNull] Fortran77Parser.EndStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dimensionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDimensionStatement([NotNull] Fortran77Parser.DimensionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dimensionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDimensionStatement([NotNull] Fortran77Parser.DimensionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arrayDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclarator([NotNull] Fortran77Parser.ArrayDeclaratorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arrayDeclarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclarator([NotNull] Fortran77Parser.ArrayDeclaratorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arrayDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclarators([NotNull] Fortran77Parser.ArrayDeclaratorsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arrayDeclarators"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclarators([NotNull] Fortran77Parser.ArrayDeclaratorsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arrayDeclaratorExtents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclaratorExtents([NotNull] Fortran77Parser.ArrayDeclaratorExtentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arrayDeclaratorExtents"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclaratorExtents([NotNull] Fortran77Parser.ArrayDeclaratorExtentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arrayDeclaratorExtent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayDeclaratorExtent([NotNull] Fortran77Parser.ArrayDeclaratorExtentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arrayDeclaratorExtent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayDeclaratorExtent([NotNull] Fortran77Parser.ArrayDeclaratorExtentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.equivalenceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquivalenceStatement([NotNull] Fortran77Parser.EquivalenceStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.equivalenceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquivalenceStatement([NotNull] Fortran77Parser.EquivalenceStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.equivEntityGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquivEntityGroup([NotNull] Fortran77Parser.EquivEntityGroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.equivEntityGroup"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquivEntityGroup([NotNull] Fortran77Parser.EquivEntityGroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.equivEntity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEquivEntity([NotNull] Fortran77Parser.EquivEntityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.equivEntity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEquivEntity([NotNull] Fortran77Parser.EquivEntityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.commonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonStatement([NotNull] Fortran77Parser.CommonStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.commonStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonStatement([NotNull] Fortran77Parser.CommonStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.commonName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonName([NotNull] Fortran77Parser.CommonNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.commonName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonName([NotNull] Fortran77Parser.CommonNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.commonItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonItem([NotNull] Fortran77Parser.CommonItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.commonItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonItem([NotNull] Fortran77Parser.CommonItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.commonItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonItems([NotNull] Fortran77Parser.CommonItemsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.commonItems"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonItems([NotNull] Fortran77Parser.CommonItemsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.commonBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCommonBlock([NotNull] Fortran77Parser.CommonBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.commonBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCommonBlock([NotNull] Fortran77Parser.CommonBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStatement([NotNull] Fortran77Parser.TypeStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStatement([NotNull] Fortran77Parser.TypeStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typeStatementNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStatementNameList([NotNull] Fortran77Parser.TypeStatementNameListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typeStatementNameList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStatementNameList([NotNull] Fortran77Parser.TypeStatementNameListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typeStatementName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStatementName([NotNull] Fortran77Parser.TypeStatementNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typeStatementName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStatementName([NotNull] Fortran77Parser.TypeStatementNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typeStatementNameCharList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStatementNameCharList([NotNull] Fortran77Parser.TypeStatementNameCharListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typeStatementNameCharList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStatementNameCharList([NotNull] Fortran77Parser.TypeStatementNameCharListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typeStatementNameChar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStatementNameChar([NotNull] Fortran77Parser.TypeStatementNameCharContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typeStatementNameChar"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStatementNameChar([NotNull] Fortran77Parser.TypeStatementNameCharContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typeStatementLenSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeStatementLenSpec([NotNull] Fortran77Parser.TypeStatementLenSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typeStatementLenSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeStatementLenSpec([NotNull] Fortran77Parser.TypeStatementLenSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typename_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypename_([NotNull] Fortran77Parser.Typename_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typename_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypename_([NotNull] Fortran77Parser.Typename_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType_([NotNull] Fortran77Parser.Type_Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.type_"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType_([NotNull] Fortran77Parser.Type_Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.typenameLen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypenameLen([NotNull] Fortran77Parser.TypenameLenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.typenameLen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypenameLen([NotNull] Fortran77Parser.TypenameLenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.pointerStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerStatement([NotNull] Fortran77Parser.PointerStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.pointerStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerStatement([NotNull] Fortran77Parser.PointerStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.pointerDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPointerDecl([NotNull] Fortran77Parser.PointerDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.pointerDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPointerDecl([NotNull] Fortran77Parser.PointerDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.implicitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitStatement([NotNull] Fortran77Parser.ImplicitStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.implicitStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitStatement([NotNull] Fortran77Parser.ImplicitStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.implicitSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitSpec([NotNull] Fortran77Parser.ImplicitSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.implicitSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitSpec([NotNull] Fortran77Parser.ImplicitSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.implicitSpecs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitSpecs([NotNull] Fortran77Parser.ImplicitSpecsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.implicitSpecs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitSpecs([NotNull] Fortran77Parser.ImplicitSpecsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.implicitNone"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitNone([NotNull] Fortran77Parser.ImplicitNoneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.implicitNone"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitNone([NotNull] Fortran77Parser.ImplicitNoneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.implicitLetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitLetter([NotNull] Fortran77Parser.ImplicitLetterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.implicitLetter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitLetter([NotNull] Fortran77Parser.ImplicitLetterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.implicitRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitRange([NotNull] Fortran77Parser.ImplicitRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.implicitRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitRange([NotNull] Fortran77Parser.ImplicitRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.implicitLetters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterImplicitLetters([NotNull] Fortran77Parser.ImplicitLettersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.implicitLetters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitImplicitLetters([NotNull] Fortran77Parser.ImplicitLettersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.lenSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLenSpecification([NotNull] Fortran77Parser.LenSpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.lenSpecification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLenSpecification([NotNull] Fortran77Parser.LenSpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.characterWithLen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterWithLen([NotNull] Fortran77Parser.CharacterWithLenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.characterWithLen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterWithLen([NotNull] Fortran77Parser.CharacterWithLenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.cwlLen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCwlLen([NotNull] Fortran77Parser.CwlLenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.cwlLen"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCwlLen([NotNull] Fortran77Parser.CwlLenContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.parameterStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterStatement([NotNull] Fortran77Parser.ParameterStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.parameterStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterStatement([NotNull] Fortran77Parser.ParameterStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.paramlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamlist([NotNull] Fortran77Parser.ParamlistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.paramlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamlist([NotNull] Fortran77Parser.ParamlistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.paramassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamassign([NotNull] Fortran77Parser.ParamassignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.paramassign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamassign([NotNull] Fortran77Parser.ParamassignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.externalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExternalStatement([NotNull] Fortran77Parser.ExternalStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.externalStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExternalStatement([NotNull] Fortran77Parser.ExternalStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.intrinsicStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntrinsicStatement([NotNull] Fortran77Parser.IntrinsicStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.intrinsicStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntrinsicStatement([NotNull] Fortran77Parser.IntrinsicStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.saveStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSaveStatement([NotNull] Fortran77Parser.SaveStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.saveStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSaveStatement([NotNull] Fortran77Parser.SaveStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.saveEntity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSaveEntity([NotNull] Fortran77Parser.SaveEntityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.saveEntity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSaveEntity([NotNull] Fortran77Parser.SaveEntityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataStatement([NotNull] Fortran77Parser.DataStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataStatement([NotNull] Fortran77Parser.DataStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataStatementItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataStatementItem([NotNull] Fortran77Parser.DataStatementItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataStatementItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataStatementItem([NotNull] Fortran77Parser.DataStatementItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataStatementMultiple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataStatementMultiple([NotNull] Fortran77Parser.DataStatementMultipleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataStatementMultiple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataStatementMultiple([NotNull] Fortran77Parser.DataStatementMultipleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataStatementEntity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataStatementEntity([NotNull] Fortran77Parser.DataStatementEntityContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataStatementEntity"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataStatementEntity([NotNull] Fortran77Parser.DataStatementEntityContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dse1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDse1([NotNull] Fortran77Parser.Dse1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dse1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDse1([NotNull] Fortran77Parser.Dse1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dse2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDse2([NotNull] Fortran77Parser.Dse2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dse2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDse2([NotNull] Fortran77Parser.Dse2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataImpliedDo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataImpliedDo([NotNull] Fortran77Parser.DataImpliedDoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataImpliedDo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataImpliedDo([NotNull] Fortran77Parser.DataImpliedDoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataImpliedDoRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataImpliedDoRange([NotNull] Fortran77Parser.DataImpliedDoRangeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataImpliedDoRange"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataImpliedDoRange([NotNull] Fortran77Parser.DataImpliedDoRangeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataImpliedDoList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataImpliedDoList([NotNull] Fortran77Parser.DataImpliedDoListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataImpliedDoList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataImpliedDoList([NotNull] Fortran77Parser.DataImpliedDoListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.dataImpliedDoListWhat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDataImpliedDoListWhat([NotNull] Fortran77Parser.DataImpliedDoListWhatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.dataImpliedDoListWhat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDataImpliedDoListWhat([NotNull] Fortran77Parser.DataImpliedDoListWhatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGotoStatement([NotNull] Fortran77Parser.GotoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.gotoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGotoStatement([NotNull] Fortran77Parser.GotoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.unconditionalGoto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnconditionalGoto([NotNull] Fortran77Parser.UnconditionalGotoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.unconditionalGoto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnconditionalGoto([NotNull] Fortran77Parser.UnconditionalGotoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.computedGoto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComputedGoto([NotNull] Fortran77Parser.ComputedGotoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.computedGoto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComputedGoto([NotNull] Fortran77Parser.ComputedGotoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.lblRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLblRef([NotNull] Fortran77Parser.LblRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.lblRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLblRef([NotNull] Fortran77Parser.LblRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.labelList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLabelList([NotNull] Fortran77Parser.LabelListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.labelList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLabelList([NotNull] Fortran77Parser.LabelListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.assignedGoto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignedGoto([NotNull] Fortran77Parser.AssignedGotoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.assignedGoto"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignedGoto([NotNull] Fortran77Parser.AssignedGotoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] Fortran77Parser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] Fortran77Parser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arithmeticIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticIfStatement([NotNull] Fortran77Parser.ArithmeticIfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arithmeticIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticIfStatement([NotNull] Fortran77Parser.ArithmeticIfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.logicalIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalIfStatement([NotNull] Fortran77Parser.LogicalIfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.logicalIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalIfStatement([NotNull] Fortran77Parser.LogicalIfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.blockIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockIfStatement([NotNull] Fortran77Parser.BlockIfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.blockIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockIfStatement([NotNull] Fortran77Parser.BlockIfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.firstIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFirstIfBlock([NotNull] Fortran77Parser.FirstIfBlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.firstIfBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFirstIfBlock([NotNull] Fortran77Parser.FirstIfBlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseIfStatement([NotNull] Fortran77Parser.ElseIfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.elseIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseIfStatement([NotNull] Fortran77Parser.ElseIfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] Fortran77Parser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] Fortran77Parser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.endIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndIfStatement([NotNull] Fortran77Parser.EndIfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.endIfStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndIfStatement([NotNull] Fortran77Parser.EndIfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.doStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoStatement([NotNull] Fortran77Parser.DoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.doStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoStatement([NotNull] Fortran77Parser.DoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.doVarArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoVarArgs([NotNull] Fortran77Parser.DoVarArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.doVarArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoVarArgs([NotNull] Fortran77Parser.DoVarArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.doWithLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWithLabel([NotNull] Fortran77Parser.DoWithLabelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.doWithLabel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWithLabel([NotNull] Fortran77Parser.DoWithLabelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.doBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoBody([NotNull] Fortran77Parser.DoBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.doBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoBody([NotNull] Fortran77Parser.DoBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.doWithEndDo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDoWithEndDo([NotNull] Fortran77Parser.DoWithEndDoContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.doWithEndDo"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDoWithEndDo([NotNull] Fortran77Parser.DoWithEndDoContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.enddoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEnddoStatement([NotNull] Fortran77Parser.EnddoStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.enddoStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEnddoStatement([NotNull] Fortran77Parser.EnddoStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] Fortran77Parser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] Fortran77Parser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.stopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStopStatement([NotNull] Fortran77Parser.StopStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.stopStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStopStatement([NotNull] Fortran77Parser.StopStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.pauseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPauseStatement([NotNull] Fortran77Parser.PauseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.pauseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPauseStatement([NotNull] Fortran77Parser.PauseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.writeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWriteStatement([NotNull] Fortran77Parser.WriteStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.writeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWriteStatement([NotNull] Fortran77Parser.WriteStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReadStatement([NotNull] Fortran77Parser.ReadStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.readStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReadStatement([NotNull] Fortran77Parser.ReadStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrintStatement([NotNull] Fortran77Parser.PrintStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.printStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrintStatement([NotNull] Fortran77Parser.PrintStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignmentStatement([NotNull] Fortran77Parser.AssignmentStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.assignmentStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignmentStatement([NotNull] Fortran77Parser.AssignmentStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlInfoList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlInfoList([NotNull] Fortran77Parser.ControlInfoListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlInfoList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlInfoList([NotNull] Fortran77Parser.ControlInfoListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlErrSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlErrSpec([NotNull] Fortran77Parser.ControlErrSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlErrSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlErrSpec([NotNull] Fortran77Parser.ControlErrSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlInfoListItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlInfoListItem([NotNull] Fortran77Parser.ControlInfoListItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlInfoListItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlInfoListItem([NotNull] Fortran77Parser.ControlInfoListItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.ioList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoList([NotNull] Fortran77Parser.IoListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.ioList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoList([NotNull] Fortran77Parser.IoListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.ioListItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoListItem([NotNull] Fortran77Parser.IoListItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.ioListItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoListItem([NotNull] Fortran77Parser.IoListItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.ioImpliedDoList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIoImpliedDoList([NotNull] Fortran77Parser.IoImpliedDoListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.ioImpliedDoList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIoImpliedDoList([NotNull] Fortran77Parser.IoImpliedDoListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.openStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenStatement([NotNull] Fortran77Parser.OpenStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.openStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenStatement([NotNull] Fortran77Parser.OpenStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.openControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpenControl([NotNull] Fortran77Parser.OpenControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.openControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpenControl([NotNull] Fortran77Parser.OpenControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlFmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlFmt([NotNull] Fortran77Parser.ControlFmtContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlFmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlFmt([NotNull] Fortran77Parser.ControlFmtContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlUnit([NotNull] Fortran77Parser.ControlUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlUnit([NotNull] Fortran77Parser.ControlUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlRec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlRec([NotNull] Fortran77Parser.ControlRecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlRec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlRec([NotNull] Fortran77Parser.ControlRecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlEnd([NotNull] Fortran77Parser.ControlEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlEnd([NotNull] Fortran77Parser.ControlEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlErr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlErr([NotNull] Fortran77Parser.ControlErrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlErr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlErr([NotNull] Fortran77Parser.ControlErrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlIostat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlIostat([NotNull] Fortran77Parser.ControlIostatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlIostat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlIostat([NotNull] Fortran77Parser.ControlIostatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlFile([NotNull] Fortran77Parser.ControlFileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlFile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlFile([NotNull] Fortran77Parser.ControlFileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlStatus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlStatus([NotNull] Fortran77Parser.ControlStatusContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlStatus"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlStatus([NotNull] Fortran77Parser.ControlStatusContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlAccess([NotNull] Fortran77Parser.ControlAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlAccess"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlAccess([NotNull] Fortran77Parser.ControlAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlPosition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlPosition([NotNull] Fortran77Parser.ControlPositionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlPosition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlPosition([NotNull] Fortran77Parser.ControlPositionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlForm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlForm([NotNull] Fortran77Parser.ControlFormContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlForm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlForm([NotNull] Fortran77Parser.ControlFormContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlRecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlRecl([NotNull] Fortran77Parser.ControlReclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlRecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlRecl([NotNull] Fortran77Parser.ControlReclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlBlank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlBlank([NotNull] Fortran77Parser.ControlBlankContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlBlank"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlBlank([NotNull] Fortran77Parser.ControlBlankContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlExist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlExist([NotNull] Fortran77Parser.ControlExistContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlExist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlExist([NotNull] Fortran77Parser.ControlExistContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlOpened"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlOpened([NotNull] Fortran77Parser.ControlOpenedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlOpened"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlOpened([NotNull] Fortran77Parser.ControlOpenedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlNumber([NotNull] Fortran77Parser.ControlNumberContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlNumber"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlNumber([NotNull] Fortran77Parser.ControlNumberContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlNamed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlNamed([NotNull] Fortran77Parser.ControlNamedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlNamed"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlNamed([NotNull] Fortran77Parser.ControlNamedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlName([NotNull] Fortran77Parser.ControlNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlName([NotNull] Fortran77Parser.ControlNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlSequential"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlSequential([NotNull] Fortran77Parser.ControlSequentialContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlSequential"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlSequential([NotNull] Fortran77Parser.ControlSequentialContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlDirect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlDirect([NotNull] Fortran77Parser.ControlDirectContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlDirect"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlDirect([NotNull] Fortran77Parser.ControlDirectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlFormatted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlFormatted([NotNull] Fortran77Parser.ControlFormattedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlFormatted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlFormatted([NotNull] Fortran77Parser.ControlFormattedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlUnformatted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlUnformatted([NotNull] Fortran77Parser.ControlUnformattedContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlUnformatted"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlUnformatted([NotNull] Fortran77Parser.ControlUnformattedContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.controlNextrec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterControlNextrec([NotNull] Fortran77Parser.ControlNextrecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.controlNextrec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitControlNextrec([NotNull] Fortran77Parser.ControlNextrecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.closeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloseStatement([NotNull] Fortran77Parser.CloseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.closeStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloseStatement([NotNull] Fortran77Parser.CloseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.closeControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCloseControl([NotNull] Fortran77Parser.CloseControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.closeControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCloseControl([NotNull] Fortran77Parser.CloseControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.inquireStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInquireStatement([NotNull] Fortran77Parser.InquireStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.inquireStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInquireStatement([NotNull] Fortran77Parser.InquireStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.inquireControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInquireControl([NotNull] Fortran77Parser.InquireControlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.inquireControl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInquireControl([NotNull] Fortran77Parser.InquireControlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.backspaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBackspaceStatement([NotNull] Fortran77Parser.BackspaceStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.backspaceStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBackspaceStatement([NotNull] Fortran77Parser.BackspaceStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.endfileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndfileStatement([NotNull] Fortran77Parser.EndfileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.endfileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndfileStatement([NotNull] Fortran77Parser.EndfileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.rewindStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRewindStatement([NotNull] Fortran77Parser.RewindStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.rewindStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRewindStatement([NotNull] Fortran77Parser.RewindStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.berFinish"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBerFinish([NotNull] Fortran77Parser.BerFinishContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.berFinish"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBerFinish([NotNull] Fortran77Parser.BerFinishContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.berFinishItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBerFinishItem([NotNull] Fortran77Parser.BerFinishItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.berFinishItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBerFinishItem([NotNull] Fortran77Parser.BerFinishItemContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.unitIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnitIdentifier([NotNull] Fortran77Parser.UnitIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.unitIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnitIdentifier([NotNull] Fortran77Parser.UnitIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.formatIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatIdentifier([NotNull] Fortran77Parser.FormatIdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.formatIdentifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatIdentifier([NotNull] Fortran77Parser.FormatIdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.formatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatStatement([NotNull] Fortran77Parser.FormatStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.formatStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatStatement([NotNull] Fortran77Parser.FormatStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.fmtSpec2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFmtSpec2([NotNull] Fortran77Parser.FmtSpec2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.fmtSpec2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFmtSpec2([NotNull] Fortran77Parser.FmtSpec2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.fmtSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFmtSpec([NotNull] Fortran77Parser.FmtSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.fmtSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFmtSpec([NotNull] Fortran77Parser.FmtSpecContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.formatsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatsep([NotNull] Fortran77Parser.FormatsepContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.formatsep"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatsep([NotNull] Fortran77Parser.FormatsepContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.formatedit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormatedit([NotNull] Fortran77Parser.FormateditContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.formatedit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormatedit([NotNull] Fortran77Parser.FormateditContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.editElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEditElement([NotNull] Fortran77Parser.EditElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.editElement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEditElement([NotNull] Fortran77Parser.EditElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.statementFunctionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatementFunctionStatement([NotNull] Fortran77Parser.StatementFunctionStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.statementFunctionStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatementFunctionStatement([NotNull] Fortran77Parser.StatementFunctionStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.sfArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSfArgs([NotNull] Fortran77Parser.SfArgsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.sfArgs"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSfArgs([NotNull] Fortran77Parser.SfArgsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallStatement([NotNull] Fortran77Parser.CallStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.callStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallStatement([NotNull] Fortran77Parser.CallStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.subroutineCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubroutineCall([NotNull] Fortran77Parser.SubroutineCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.subroutineCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubroutineCall([NotNull] Fortran77Parser.SubroutineCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.callArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallArgumentList([NotNull] Fortran77Parser.CallArgumentListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.callArgumentList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallArgumentList([NotNull] Fortran77Parser.CallArgumentListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.callArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCallArgument([NotNull] Fortran77Parser.CallArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.callArgument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCallArgument([NotNull] Fortran77Parser.CallArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] Fortran77Parser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] Fortran77Parser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] Fortran77Parser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] Fortran77Parser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.ncExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNcExpr([NotNull] Fortran77Parser.NcExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.ncExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNcExpr([NotNull] Fortran77Parser.NcExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.lexpr0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexpr0([NotNull] Fortran77Parser.Lexpr0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.lexpr0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexpr0([NotNull] Fortran77Parser.Lexpr0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.lexpr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexpr1([NotNull] Fortran77Parser.Lexpr1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.lexpr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexpr1([NotNull] Fortran77Parser.Lexpr1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.lexpr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexpr2([NotNull] Fortran77Parser.Lexpr2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.lexpr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexpr2([NotNull] Fortran77Parser.Lexpr2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.lexpr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexpr3([NotNull] Fortran77Parser.Lexpr3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.lexpr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexpr3([NotNull] Fortran77Parser.Lexpr3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.lexpr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLexpr4([NotNull] Fortran77Parser.Lexpr4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.lexpr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLexpr4([NotNull] Fortran77Parser.Lexpr4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.aexpr0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAexpr0([NotNull] Fortran77Parser.Aexpr0Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.aexpr0"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAexpr0([NotNull] Fortran77Parser.Aexpr0Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.aexpr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAexpr1([NotNull] Fortran77Parser.Aexpr1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.aexpr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAexpr1([NotNull] Fortran77Parser.Aexpr1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.aexpr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAexpr2([NotNull] Fortran77Parser.Aexpr2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.aexpr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAexpr2([NotNull] Fortran77Parser.Aexpr2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.aexpr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAexpr3([NotNull] Fortran77Parser.Aexpr3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.aexpr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAexpr3([NotNull] Fortran77Parser.Aexpr3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.aexpr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAexpr4([NotNull] Fortran77Parser.Aexpr4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.aexpr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAexpr4([NotNull] Fortran77Parser.Aexpr4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.iexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIexpr([NotNull] Fortran77Parser.IexprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.iexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIexpr([NotNull] Fortran77Parser.IexprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.iexprCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIexprCode([NotNull] Fortran77Parser.IexprCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.iexprCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIexprCode([NotNull] Fortran77Parser.IexprCodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.iexpr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIexpr1([NotNull] Fortran77Parser.Iexpr1Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.iexpr1"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIexpr1([NotNull] Fortran77Parser.Iexpr1Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.iexpr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIexpr2([NotNull] Fortran77Parser.Iexpr2Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.iexpr2"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIexpr2([NotNull] Fortran77Parser.Iexpr2Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.iexpr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIexpr3([NotNull] Fortran77Parser.Iexpr3Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.iexpr3"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIexpr3([NotNull] Fortran77Parser.Iexpr3Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.iexpr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIexpr4([NotNull] Fortran77Parser.Iexpr4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.iexpr4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIexpr4([NotNull] Fortran77Parser.Iexpr4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.constantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantExpr([NotNull] Fortran77Parser.ConstantExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.constantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantExpr([NotNull] Fortran77Parser.ConstantExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticExpression([NotNull] Fortran77Parser.ArithmeticExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arithmeticExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticExpression([NotNull] Fortran77Parser.ArithmeticExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.integerExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntegerExpr([NotNull] Fortran77Parser.IntegerExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.integerExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntegerExpr([NotNull] Fortran77Parser.IntegerExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.intRealDpExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntRealDpExpr([NotNull] Fortran77Parser.IntRealDpExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.intRealDpExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntRealDpExpr([NotNull] Fortran77Parser.IntRealDpExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arithmeticConstExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArithmeticConstExpr([NotNull] Fortran77Parser.ArithmeticConstExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arithmeticConstExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArithmeticConstExpr([NotNull] Fortran77Parser.ArithmeticConstExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.intConstantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntConstantExpr([NotNull] Fortran77Parser.IntConstantExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.intConstantExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntConstantExpr([NotNull] Fortran77Parser.IntConstantExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.characterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharacterExpression([NotNull] Fortran77Parser.CharacterExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.characterExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharacterExpression([NotNull] Fortran77Parser.CharacterExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.concatOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConcatOp([NotNull] Fortran77Parser.ConcatOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.concatOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConcatOp([NotNull] Fortran77Parser.ConcatOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalExpression([NotNull] Fortran77Parser.LogicalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.logicalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalExpression([NotNull] Fortran77Parser.LogicalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.logicalConstExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalConstExpr([NotNull] Fortran77Parser.LogicalConstExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.logicalConstExpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalConstExpr([NotNull] Fortran77Parser.LogicalConstExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arrayElementName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayElementName([NotNull] Fortran77Parser.ArrayElementNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arrayElementName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayElementName([NotNull] Fortran77Parser.ArrayElementNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubscripts([NotNull] Fortran77Parser.SubscriptsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.subscripts"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubscripts([NotNull] Fortran77Parser.SubscriptsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarRef([NotNull] Fortran77Parser.VarRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarRef([NotNull] Fortran77Parser.VarRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.varRefCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarRefCode([NotNull] Fortran77Parser.VarRefCodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.varRefCode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarRefCode([NotNull] Fortran77Parser.VarRefCodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.substringApp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubstringApp([NotNull] Fortran77Parser.SubstringAppContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.substringApp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubstringApp([NotNull] Fortran77Parser.SubstringAppContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableName([NotNull] Fortran77Parser.VariableNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableName([NotNull] Fortran77Parser.VariableNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.arrayName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayName([NotNull] Fortran77Parser.ArrayNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.arrayName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayName([NotNull] Fortran77Parser.ArrayNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.subroutineName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubroutineName([NotNull] Fortran77Parser.SubroutineNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.subroutineName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubroutineName([NotNull] Fortran77Parser.SubroutineNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionName([NotNull] Fortran77Parser.FunctionNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.functionName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionName([NotNull] Fortran77Parser.FunctionNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] Fortran77Parser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] Fortran77Parser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.unsignedArithmeticConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnsignedArithmeticConstant([NotNull] Fortran77Parser.UnsignedArithmeticConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.unsignedArithmeticConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnsignedArithmeticConstant([NotNull] Fortran77Parser.UnsignedArithmeticConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.complexConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterComplexConstant([NotNull] Fortran77Parser.ComplexConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.complexConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitComplexConstant([NotNull] Fortran77Parser.ComplexConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.logicalConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalConstant([NotNull] Fortran77Parser.LogicalConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.logicalConstant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalConstant([NotNull] Fortran77Parser.LogicalConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdentifier([NotNull] Fortran77Parser.IdentifierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdentifier([NotNull] Fortran77Parser.IdentifierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Fortran77Parser.to"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTo([NotNull] Fortran77Parser.ToContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Fortran77Parser.to"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTo([NotNull] Fortran77Parser.ToContext context);
}
