name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      version: 0.9.0-debug-${{ github.run_number }}
  
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build DEBUG
      run: dotnet build --no-restore -p:RELEASE_VERSION=${{ env.version }}
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Build Release
      run: dotnet build --no-restore -c Release -p:RELEASE_VERSION=0.9.0-prerelease.${{env.GITHUB_RUN_NUMBER}}
